### PR TITLE
Mp 013 widgets

### PR DESCRIPTION
**Pull request by MorganPeterson**
Red Flag Parameter widgets installed per issue 46

Make sure to run configure.js to ensure that parameter defaults are correct.

### CODE REVIEW

**Comment by bkj** [comment]
Would be good to spend half an hour polishing the CSS so we can merge this and forget about it

**Comment by MorganPeterson** [comment]
This is on my TODO list. I will have it done this week.

**Comment by MorganPeterson** [comment]
I used Bootstrap to clean up the forms.

**Comment by bkj** [comment]
Merged

**Pull request merged**
